apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-deployment
  namespace: default
  labels:
    app: tukano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano
  template:
    metadata:
      labels:
        app: tukano
    spec:
      containers:
        - name: tukano-container
          image: t1santos/tukanoimage:latest  # Replace with your actual Docker image
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: tukano-service
  namespace: default
  labels:
    app: tukano
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tukano
